#include "page.h"

pte_t ppn2[] = {
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
  (pte_t)(PTE_V | PTE_X | PTE_W | PTE_R),
};