#ifndef VIRT_H
#define VIRT_H

#define VIRT_MMIO_MASIC 0x00
#define VIRT_MMIO_VERSION 0x04
#define VIRT_MMIO_DEVICEID 0x08
#define VIRT_MMIO_VENDERID 0x0c
#define VIRT_MMIO_DEVICE_FEATURES 0x10
#define VIRT_MMIO_DEVICE_FEATURES_SEL 0x14
#define VIRT_MMIO_DRIVER_FEATURES 0x20
#define VIRT_MMIO_DRIVER_FEATURES_SEL 0x24
#define VIRT_MMIO_QUEUE_SEL 0x30
#define VIRT_MMIO_QUEUE_MAX 0x34
#define VIRT_MMIO_QUEUE_NUM 0x38
#define VIRT_MMIO_QUEUE_READY 0x44
#define VIRT_MMIO_QUEUE_NOTIFY 0x50
#define VIRT_MMIO_INTR_STAT 0x60
#define VIRT_MMIO_INTR_ACK 0x64
#define VIRT_MMIO_DEVICE_STAT 0x70
#define VIRT_MMIO_QUEUE_DESC_LOW 0x80
#define VIRT_MMIO_QUEUE_DESC_HIGH 0x84
#define VIRT_MMIO_QUEUE_DRIVER_LOW 0x90
#define VIRT_MMIO_QUEUE_DRIVER_HIGH 0x94
#define VIRT_MMIO_QUEUE_DEVICE_LOW 0xa0
#define VIRT_MMIO_QUEUE_DEVICE_HIGH 0xa4
#define VIRT_MMIO_CONFIG 0xfc